### ISSUE TITLE
seg fault generating for wasi-http

### ISSUE THREAD

**Issue by brendandburns** [ydnar/wasm-tools-go#151]
```sh
~/go/bin/wit-bindgen-go generate wasi-http.json 
Output dir: .
Package root: github.com/dev-wasm/dev-wasm-go/lib/wasi
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61e772]

goroutine 1 [running]:
github.com/ydnar/wasm-tools-go/wit/bindgen.(*generator).defineInterface(0xc0000e4600, 0x0, 0x0, {0xc000104b73, 0xb})
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/bindgen/generator.go:310 +0xf2
github.com/ydnar/wasm-tools-go/wit/bindgen.(*generator).defineWorld.func1({0xc000104b73?, 0x6b2049?}, {0x711dc8?, 0xc000106438?})
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/bindgen/generator.go:273 +0xcc
github.com/ydnar/wasm-tools-go/wit/bindgen.(*generator).defineWorld.(*Map[...]).all.func3()
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/ordered/list.go:15 +0x54
github.com/ydnar/wasm-tools-go/wit/bindgen.(*generator).defineWorld(0xc0000e4600, 0xc0000eeb00)
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/bindgen/generator.go:269 +0x531
github.com/ydnar/wasm-tools-go/wit/bindgen.(*generator).defineWorlds(0xc0000e4600)
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/bindgen/generator.go:230 +0xa5
github.com/ydnar/wasm-tools-go/wit/bindgen.(*generator).generate(0xc0000e4600)
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/bindgen/generator.go:180 +0x2c
github.com/ydnar/wasm-tools-go/wit/bindgen.Go(0x8c3be0?, {0xc00008b6e8?, 0x2?, 0x11?})
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/wit/bindgen/generate.go:15 +0x35
github.com/ydnar/wasm-tools-go/cmd/wit-bindgen-go/cmd/generate.action({0x8c3be0?, 0x8?}, 0x8c3be0)
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/cmd/wit-bindgen-go/cmd/generate/generate.go:95 +0x558
github.com/urfave/cli/v3.(*Command).Run(0x8c3be0, {0x712a20, 0xc0000a2990}, {0xc0000ca420, 0x2, 0x2})
        /root/go/pkg/mod/github.com/urfave/cli/v3@v3.0.0-alpha9/command.go:647 +0x19a8
github.com/urfave/cli/v3.(*Command).Run(0xc0000da288, {0x7129e8, 0x8e7fa0}, {0xc0000a2270, 0x3, 0x3})
        /root/go/pkg/mod/github.com/urfave/cli/v3@v3.0.0-alpha9/command.go:620 +0x1945
main.main()
        /root/go/pkg/mod/github.com/ydnar/wasm-tools-go@v0.1.5/cmd/wit-bindgen-go/main.go:51 +0x23e
```

`wasi-http.json` is attached and is generated using `wasm-tools` from https://github.com/WebAssembly/wasi-http
[wasi-http.json](https://github.com/user-attachments/files/16788890/wasi-http.json)

**Comment by rajatjindal** [comment]
I just tried this with latest version of wasm-tools, wasm-tools-go and latest wit files from WebAssembly, and seems to have worked for me but fails for the json file that you have attached. 

could you please share how the json file was generated, and which version of wasm-tools was used for that? thanks

```
~/go/src/github.com/WebAssembly/wasi-http git:(main)
$ git remote -v                                                  
origin  ssh://git@github.com/WebAssembly/wasi-http (fetch)
origin  ssh://git@github.com/WebAssembly/wasi-http (push)

~/go/src/github.com/WebAssembly/wasi-http git:(main)
$ git pull --rebase
Already up to date.

~/go/src/github.com/WebAssembly/wasi-http (cloud-docker/ap-south-1) git:(main)
$ ~/Downloads/wasm-tools-1.216.0-aarch64-macos/wasm-tools component wit ./wit --json > wit2.json

~/go/src/github.com/WebAssembly/wasi-http (cloud-docker/ap-south-1) git:(main)
$ cd ../../ydnar/wasm-tools-go 

~/go/src/github.com/ydnar/wasm-tools-go (cloud-docker/ap-south-1) git:(main)
$ git remote -v
origin  git@github.com:rajatjindal/wasm-tools-go.git (fetch)
origin  git@github.com:rajatjindal/wasm-tools-go.git (push)
upstream        git@github.com:ydnar/wasm-tools-go.git (fetch)
upstream        git@github.com:ydnar/wasm-tools-go.git (push)

~/go/src/github.com/ydnar/wasm-tools-go (cloud-docker/ap-south-1) git:(main) 
$ git fetch upstream

~/go/src/github.com/ydnar/wasm-tools-go (cloud-docker/ap-south-1) git:(main) 
$ git rebase upstream/main
Current branch main is up to date.

~/go/src/github.com/ydnar/wasm-tools-go (cloud-docker/ap-south-1) git:(main)
$ go build -o wit-bindgen-go cmd/wit-bindgen-go/main.go          

~/go/src/github.com/ydnar/wasm-tools-go (cloud-docker/ap-south-1) git:(main)
$ ./wit-bindgen-go generate ../../WebAssembly/wasi-http/wit2.json                      
         
Output dir: .
Package root: github.com/ydnar/wasm-tools-go
Generated 13 package(s)
Generated package: github.com/ydnar/wasm-tools-go/wasi/cli/stderr
Generated file: wasi/cli/stderr/empty.s
Generated file: wasi/cli/stderr/stderr.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/cli/stdin
Generated file: wasi/cli/stdin/empty.s
Generated file: wasi/cli/stdin/stdin.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/cli/stdout
Generated file: wasi/cli/stdout/empty.s
Generated file: wasi/cli/stdout/stdout.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/clocks/monotonic-clock
Generated file: wasi/clocks/monotonic-clock/empty.s
Generated file: wasi/clocks/monotonic-clock/monotonic-clock.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/clocks/wall-clock
Generated file: wasi/clocks/wall-clock/empty.s
Generated file: wasi/clocks/wall-clock/wall-clock.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/http/incoming-handler
Generated file: wasi/http/incoming-handler/empty.s
Generated file: wasi/http/incoming-handler/incoming-handler.exports.go
Generated file: wasi/http/incoming-handler/incoming-handler.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/http/outgoing-handler
Generated file: wasi/http/outgoing-handler/abi.go
Generated file: wasi/http/outgoing-handler/empty.s
Generated file: wasi/http/outgoing-handler/outgoing-handler.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/http/proxy
Generated file: wasi/http/proxy/proxy.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/http/types
Generated file: wasi/http/types/abi.go
Generated file: wasi/http/types/empty.s
Generated file: wasi/http/types/types.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/io/error
Generated file: wasi/io/error/empty.s
Generated file: wasi/io/error/error.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/io/poll
Generated file: wasi/io/poll/empty.s
Generated file: wasi/io/poll/poll.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/io/streams
Generated file: wasi/io/streams/abi.go
Generated file: wasi/io/streams/empty.s
Generated file: wasi/io/streams/streams.wit.go
Generated package: github.com/ydnar/wasm-tools-go/wasi/random/random
Generated file: wasi/random/random/empty.s
Generated file: wasi/random/random/random.wit.go
~/go/src/github.com/ydnar/wasm-tools-go (cloud-docker/ap-south-1) git:(main)
$ 
```

**Comment by ydnar** [comment]
👋 @brendandburns, I'll take a look when I'm back at my desk. 

The JSON format emitted by wasm-tools is somewhat unstable. For instance the addition of feature gates broke this package. 

wit-bindgen-go will shell out to wasm-tools to parse a WIT file or directory into the JSON representation, and consume it directly. Have you tried this?

**Comment by ydnar** [comment]
@brendandburns I submitted a PR (#152) that adds support for older versions of `wasm-tools` without feature gate support. You can give that branch a shot, or update your copy of `wasm-tools` to generate JSON compatible with the current releae of this package.
